### ISSUE TITLE
Inver read logic

### ISSUE THREAD

**Issue by varna33** [rsg98/homebridge-gpio-wpi2#14]
Is there a setting that would allow to invert also read?
Instead of putting the GPIO pin on 3.3v to give closed, but to give open status?

Janis

**Comment by rsg98** [comment]
Adding "inverted": "true" should work for read as well. Make sure that you have "overrideCache" set to true as well, so that this setting is read from your config file rather than the cache.

Depending on how you've wired up the sensor, you might need to set "pull": "up" or "pull": "down" (down sets active_low, up sets active_high - see https://wiki.openwrt.org/doc/hardware/port.gpio for example circuits)

**Comment by varna33** [comment]
Thank you, with resistor circuit it works perfect! I though it would be possible simply to put 3.3V on pin and it would work too.

Janis
